Changed<-which(beren3$event=="bottle")
avgUrine<-mean(beren3$event=="bottle")
avgChange<-tapply(beren3$value[Changed],beren3$age[Changed],mean)
varChange<-tapply(beren3$value[Changed],beren3$age[Changed],var)
totalChange<-tapply(beren3$value[Changed],beren3$age[Changed],sum)
numChanged<-tapply(beren3$value[Changed],beren3$age[Changed],length)
cor(beren3$value[Changed],beren3$age[Changed])
cor.test(beren3$value[Changed],beren3$age[Changed])
berenCor<-cor.test(beren3$value[Changed],beren3$age[Changed])
summary(berenCor)
berenANOVA<-aov(beren3$value[Changed]~beren3$caregiver[Changed])
boxplot(beren3$value[Changed]~beren3$caregiver[Changed],xlab="who changed the diaper",ylab="amount of times urinated")
plot(as.numeric(names(totalChange)),totalChange,type="b",pch=16,xlab="age in days",ylab="amount of times urinated")
abline(h=mean(totalChange),lty=2,col='red')
pdf("r02c-totalDiaperChangeByDaypdf",height=4,width=4)
par(las=1,mar=c(5,5,1,1),mgp=c(2,0.5,0),tck=-0.01)
plot(as.numeric(names(totalChange)),totalChange,type="b",pch=16,xlab="age in days",ylab="amount of times urinated")
abline(h=mean(totalChange),lty=2,col='red')
dev.off()